---
- name: First acme 
  hosts: all

  tasks:

    - name: Ensure the account exists
      community.crypto.acme_account:
        account_key_content: "{{ private_key }}"
        state: present
        terms_agreed: true
        contact: 
          - mailto: withjigs@yahoo.com