---
- name: First acme 
  hosts: all
  become: true

  vars:
    domain: "www4.jigar.au.eu.org"

  tasks:
        
      - name: Ensure the account exists
        community.crypto.acme_account:
          account_key_content: "{{ private_key }}"
          state: present
          terms_agreed: true
          acme_version: 2
          acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
          contact: 
            - mailto:withjigs@yahoo.com
      
      - name: Create directory to store keys
        ansible.builtin.file:
          path: "/etc/letsencrypt/archive/{{ domain }}"
          state: directory
          owner: root
          group: root
          mode: '0750'
      
      - name: Create private key for domain
        community.crypto.openssl_privatekey:
          path: "/etc/letsencrypt/archive/{{ domain }}/private_key.pem"
          type: RSA
          size: 4096

      - name: Generate CSR
        community.crypto.openssl_csr:
          path: "/etc/letsencrypt/archive/{{ domain }}/csr.pem"
          privatekey_path: "/etc/letsencrypt/archive/{{ domain }}/private_key.pem"
          common_name: "{{ domain }}"
          state_or_province_name: "VIC"
          country_name: AU
          organization_name: JigarOrg
          subject_alt_name: "DNS:cert1.jigar.au.eu.org,DNS:m.jigar.au.eu.org"


      - name: Request certificate
        community.crypto.acme_certificate:
          account_key_content: "{{ private_key }}"
          acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory          
          csr: "/etc/letsencrypt/archive/{{ domain }}/csr.pem"
          fullchain_dest: "/etc/letsencrypt/archive/{{ domain }}/fullchain.pem"
          acme_version: 2
          modify_account: false