---
- name: First acme 
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Request certificate
      ansible.builtin.import_role:
        name: acme_cert
      vars:
        acme_certificate_domain: "www7.jigar.au.eu.org"
        acme_certificate_zone: "jigar.au.eu.org"
        acme_cert_SANs:
          - "m2.jigar.au.eu.org"
          - "s2.jigar.au.eu.org"
    
    - name: Print cert
      ansible.builtin.shell:
        cmd: "cat {{ acme_keystore_base_path }}/{{acme_certificate_domain}}/cert.pem"